"""add unique constraints for one-to-one relations

Revision ID: a28c774864ea
Revises: b54a50aa8c8e
Create Date: 2026-06-20 17:42:36.763626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a28c774864ea'
down_revision: Union[str, Sequence[str], None] = 'b54a50aa8c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_candidate_ai_scores_candidate_id'), 'candidate_ai_scores', ['candidate_id'])
    op.create_unique_constraint(op.f('uq_candidates_resume_id'), 'candidates', ['resume_id'])
    op.create_unique_constraint(op.f('uq_dingding_user_user_id'), 'dingding_user', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_dingding_user_user_id'), 'dingding_user', type_='unique')
    op.drop_constraint(op.f('uq_candidates_resume_id'), 'candidates', type_='unique')
    op.drop_constraint(op.f('uq_candidate_ai_scores_candidate_id'), 'candidate_ai_scores', type_='unique')
    # ### end Alembic commands ###
